#--------------------------------------------
# Client config options
#--------------------------------------------

personalRepoUrl: git@github.com:davidxll/booksmart.git

# write here your personal configuration
dev:
 host: 169.254.134.164:4443
 backend_host: 45.55.73.28:4445

devremote:
 host: 45.55.73.28:4443
 backend_host: 45.55.73.28:4445

# pre - production
preprod:
 host: smart-prepro.securitytrfx.com
 backend_host: api-smart.securitytrfx.com

# production
prod:
 host: smart.securitytrfx.com
 backend_host: api-smart.securitytrfx.com

selected_enviroment: dev

# Note: **smart.securitytrfx.com** just gonna contain the static client
# side code(if something changes in the server we must push to 45.55.73.28:4443)
